#!/usr/bin/env bash

source "$HOME/.config/sketchybar/variables.sh" # Loads all defined colors

# General bar and Aerospace
source "$ITEM_DIR/bar.sh"
source "$ITEM_DIR/aerospace.sh"

# Left
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/media_controls.sh"

# Center (of notch)
source "$ITEM_DIR/music.sh"

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/cpu.sh"

#################### Finalizing Setup ####################

sketchybar --hotload true

sketchybar --update

while true; do
  sketchybar --trigger music_tick
  sleep .1
done
&

echo "sketchybar configuration loaded.."
